# /// script
# requires-python = ">=3.9"
# dependencies = [
#     "cryptography",
# ]
# ///

"""
Build script for Language Transfer Japanese course.
Reads all tracks_*.json files, merges them, and generates data.js.
If a PASSWORD file is present, encrypts the data using AES-GCM and PBKDF2.

Usage: uv run build.py
"""

import json
import glob
import os
import base64
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "data.js")

def main():
    # Find all track JSON files, sorted
    pattern = os.path.join(SCRIPT_DIR, "tracks_*.json")
    files = sorted(glob.glob(pattern))

    if not files:
        print("❌ No tracks_*.json files found.")
        return

    all_tracks = []
    course_meta = {}

    for f in files:
        print(f"  📖 Reading {os.path.basename(f)}")
        with open(f, "r", encoding="utf-8") as fh:
            data = json.load(fh)

        if not course_meta:
            course_meta = {
                "courseName": data.get("courseName", "Language Transfer Japanese"),
                "version": data.get("version", "0.1"),
                "description": data.get("description", ""),
                "notes": data.get("notes", ""),
            }

        all_tracks.extend(data.get("tracks", []))

    all_tracks.sort(key=lambda t: t["id"])
    merged = {**course_meta, "tracks": all_tracks}

    # Check for PASSWORD file
    pwd_file = os.path.join(SCRIPT_DIR, "PASSWORD")
    password = None
    if os.path.exists(pwd_file):
        with open(pwd_file, "r") as f:
            password = f.read().strip()

    if password:
        print("  🔒 PASSWORD file found. Encrypting data with AES-GCM...")
        json_str = json.dumps(merged, separators=(',', ':'), ensure_ascii=False)
        salt = os.urandom(16)
        
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=100000,
        )
        key = kdf.derive(password.encode("utf-8"))
        
        aesgcm = AESGCM(key)
        iv = os.urandom(12)
        ciphertext = aesgcm.encrypt(iv, json_str.encode("utf-8"), None)
        
        output_obj = {
            "encrypted": True,
            "salt": base64.b64encode(salt).decode("utf-8"),
            "iv": base64.b64encode(iv).decode("utf-8"),
            "ciphertext": base64.b64encode(ciphertext).decode("utf-8")
        }
    else:
        output_obj = merged

    # Write data.js
    with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by build.py — do not edit by hand\n")
        out.write("// Source: " + ", ".join(os.path.basename(f) for f in files) + "\n")
        out.write("const COURSE_DATA = ")
        json.dump(output_obj, out, indent=2, ensure_ascii=False)
        out.write(";\n")

    track_ids = [t["id"] for t in all_tracks]
    total_steps = sum(len(t["steps"]) for t in all_tracks)
    status = "Encrypted" if password else "Plaintext"
    print(f"\n  ✅ data.js generated ({status}) — {len(all_tracks)} tracks ({track_ids[0]}–{track_ids[-1]}), {total_steps} total steps")


if __name__ == "__main__":
    main()
