# /// script
# requires-python = ">=3.9"
# dependencies = [
#     "cryptography",
# ]
# ///

"""
Build script for Language Transfer courses (Japanese & Chinese).
Reads tracks_*.json and chinese_tracks_*.json files, merges them, and generates data.js
with JAPANESE_COURSE_DATA and CHINESE_COURSE_DATA variables.
If a PASSWORD file is present, encrypts the data using AES-GCM and PBKDF2.

Usage: uv run build.py
"""

import json
import glob
import os
import base64
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_FILE = os.path.join(SCRIPT_DIR, "data.js")

def build_course(files, default_name, password):
    if not files:
        return {"courseName": default_name, "version": "0.1", "tracks": []}, 0, 0, 0, 0

    all_tracks = []
    course_meta = {}

    for f in files:
        print(f"  📖 Reading {os.path.basename(f)}")
        with open(f, "r", encoding="utf-8") as fh:
            data = json.load(fh)

        if not course_meta:
            course_meta = {
                "courseName": data.get("courseName", default_name),
                "version": data.get("version", "0.1"),
                "description": data.get("description", ""),
                "notes": data.get("notes", ""),
            }

        all_tracks.extend(data.get("tracks", []))

    all_tracks.sort(key=lambda t: t["id"])
    merged = {**course_meta, "tracks": all_tracks}

    if password:
        json_str = json.dumps(merged, separators=(',', ':'), ensure_ascii=False)
        salt = os.urandom(16)
        
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=32,
            salt=salt,
            iterations=100000,
        )
        key = kdf.derive(password.encode("utf-8"))
        
        aesgcm = AESGCM(key)
        iv = os.urandom(12)
        ciphertext = aesgcm.encrypt(iv, json_str.encode("utf-8"), None)
        
        output_obj = {
            "encrypted": True,
            "salt": base64.b64encode(salt).decode("utf-8"),
            "iv": base64.b64encode(iv).decode("utf-8"),
            "ciphertext": base64.b64encode(ciphertext).decode("utf-8")
        }
    else:
        output_obj = merged

    track_ids = [t["id"] for t in all_tracks] if all_tracks else [0]
    total_steps = sum(len(t["steps"]) for t in all_tracks)
    return output_obj, len(all_tracks), track_ids[0], track_ids[-1], total_steps

def main():
    jp_files = sorted([f for f in glob.glob(os.path.join(SCRIPT_DIR, "tracks_*.json")) if not os.path.basename(f).startswith("chinese_")])
    zh_files = sorted(glob.glob(os.path.join(SCRIPT_DIR, "chinese_tracks_*.json")))

    if not jp_files and not zh_files:
        print("❌ No track JSON files found.")
        return

    pwd_file = os.path.join(SCRIPT_DIR, "PASSWORD")
    password = None
    if os.path.exists(pwd_file):
        with open(pwd_file, "r") as f:
            password = f.read().strip()
        print("  🔒 PASSWORD file found. Encrypting data with AES-GCM...")

    print("\n[Japanese Course]")
    jp_obj, jp_cnt, jp_first, jp_last, jp_steps = build_course(jp_files, "Language Transfer Japanese", password)

    print("\n[Chinese Course]")
    zh_obj, zh_cnt, zh_first, zh_last, zh_steps = build_course(zh_files, "Language Transfer Mandarin Chinese", password)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as out:
        out.write("// Auto-generated by build.py — do not edit by hand\n")
        all_sources = [os.path.basename(f) for f in jp_files + zh_files]
        out.write("// Source: " + ", ".join(all_sources) + "\n\n")
        out.write("const JAPANESE_COURSE_DATA = ")
        json.dump(jp_obj, out, indent=2, ensure_ascii=False)
        out.write(";\n\n")
        out.write("const CHINESE_COURSE_DATA = ")
        json.dump(zh_obj, out, indent=2, ensure_ascii=False)
        out.write(";\n\n")
        out.write("// Fallback alias\nconst COURSE_DATA = JAPANESE_COURSE_DATA;\n")

    status = "Encrypted" if password else "Plaintext"
    print(f"\n  ✅ data.js generated ({status}):")
    print(f"     🇯🇵 Japanese: {jp_cnt} tracks ({jp_first}–{jp_last}), {jp_steps} steps")
    print(f"     🇨🇳 Chinese:  {zh_cnt} tracks ({zh_first}–{zh_last}), {zh_steps} steps")

if __name__ == "__main__":
    main()
